<template>
  <div id="app">
    <div id="explicadorLogo" >
      <center> <img alt="Explicador" src="./assets/logo-novo2.png" /> </center> 
    </div>
    
    <br> <br>
    <img alt="Vue logo" src="./assets/logo.png" />
    <HelloWorld msg="Bem Vindo ao Curso do VueJS!!!" />
    <div class="loadingio-spinner-pulse-2scwkbxbq18">
      <div class="ldio-beyot08h19b">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld.vue";

export default {
  name: "App",
  components: {
    HelloWorld,
  },
};
</script>

<style type="text/css">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

#explicadorLogo{
  background-color: blue;
  width: fit-content;
  margin: auto;
}

@keyframes ldio-beyot08h19b-1 {
  0% {
    top: 36px;
    height: 128px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-beyot08h19b-2 {
  0% {
    top: 41.99999999999999px;
    height: 116.00000000000001px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
@keyframes ldio-beyot08h19b-3 {
  0% {
    top: 48px;
    height: 104px;
  }
  50% {
    top: 60px;
    height: 80px;
  }
  100% {
    top: 60px;
    height: 80px;
  }
}
.ldio-beyot08h19b div {
  position: absolute;
  width: 30px;
}
.ldio-beyot08h19b div:nth-child(1) {
  left: 35px;
  background: #e15b64;
  animation: ldio-beyot08h19b-1 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.2s;
}
.ldio-beyot08h19b div:nth-child(2) {
  left: 85px;
  background: #f8b26a;
  animation: ldio-beyot08h19b-2 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.1s;
}
.ldio-beyot08h19b div:nth-child(3) {
  left: 135px;
  background: #abbd81;
  animation: ldio-beyot08h19b-3 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: undefineds;
}

.loadingio-spinner-pulse-2scwkbxbq18 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-beyot08h19b {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-beyot08h19b div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
